version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=hamza
  frontend: 
    depends_on:
      - db
    restart: always
    ports:
      - 3000:3000
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:hamza@localhost:5432/postgres